### ISSUE TITLE
please provide an object to import

### ISSUE THREAD

**Issue by fommil** [drivergroup/spray-json-derivation#4]
in 0.1.1 it was possible to simply import this object's contents

```
    import xyz.driver.json.DerivedFormats._
```

but it is now gone, which makes it a lot harder to use this library :-(

**Comment by fommil** [comment]
note, I'm using this library in my book! https://leanpub.com/fpmortals/read#leanpub-auto-functionality-1

**Comment by jodersky** [comment]
Will do!

**Comment by jodersky** [comment]
Format companion objects were added back in 0.3.1

**Comment by fommil** [comment]
Thanks!
